import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { VoComparisonResults } from '../BimEngine';
import { buildCommercialBreakdown } from '../BimEngine';
import type { BqMappingContext } from '../BimEngine';

interface PdfReportOptions {
  projectName?: string;
  baseModelName?: string;
  revisionModelName?: string;
  pricingContext?: BqMappingContext;
  preparedBy?: string;
  date?: string;
}

export function generateVoPdfReport(results: VoComparisonResults, options: PdfReportOptions = {}): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  const now = options.date || new Date().toLocaleDateString('en-MY', { year: 'numeric', month: 'long', day: 'numeric' });

  // ── Cover Page ──────────────────────────────────────────────────────────────
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 297, 'F');

  doc.setTextColor(59, 130, 246); // blue-500
  doc.setFontSize(28);
  doc.text('VARIATION ORDER', pageWidth / 2, 80, { align: 'center' });
  doc.setFontSize(20);
  doc.text('Substantiation Report', pageWidth / 2, 95, { align: 'center' });

  doc.setTextColor(148, 163, 184); // slate-400
  doc.setFontSize(12);
  if (options.projectName) {
    doc.text(`Project: ${options.projectName}`, pageWidth / 2, 130, { align: 'center' });
  }
  doc.text(`Base: ${options.baseModelName ?? 'N/A'}`, pageWidth / 2, 145, { align: 'center' });
  doc.text(`Revision: ${options.revisionModelName ?? 'N/A'}`, pageWidth / 2, 155, { align: 'center' });
  doc.text(`Date: ${now}`, pageWidth / 2, 175, { align: 'center' });
  if (options.preparedBy) {
    doc.text(`Prepared by: ${options.preparedBy}`, pageWidth / 2, 185, { align: 'center' });
  }

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text('Generated by VO System — VO Copilot', pageWidth / 2, 260, { align: 'center' });

  // ── Summary Page ────────────────────────────────────────────────────────────
  doc.addPage();
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(16);
  doc.text('1. Executive Summary', margin, 25);

  const summaryData = [
    ['Added Elements', String(results.added.length)],
    ['Deleted Elements', String(results.deleted.length)],
    ['Modified Elements', String(results.modified.length)],
    ['Total Changes', String(results.added.length + results.deleted.length + results.modified.length)],
  ];

  if (results.qsSummary) {
    const qs = results.qsSummary;
    if (qs.formworkAlerts) summaryData.push(['Formwork Alerts', String(qs.formworkAlerts)]);
    if (qs.eotFlags) summaryData.push(['EOT Flags', String(qs.eotFlags)]);
    if (qs.starRateCandidates) summaryData.push(['Star Rate Candidates', String(qs.starRateCandidates)]);
  }

  autoTable(doc, {
    startY: 35,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    styles: { fontSize: 10 },
    headStyles: { fillColor: [59, 130, 246] },
    columnStyles: { 0: { cellWidth: contentWidth * 0.6 }, 1: { cellWidth: contentWidth * 0.4, halign: 'right' } },
    margin: { left: margin, right: margin },
  });

  // ── Commercial Breakdown ────────────────────────────────────────────────────
  const breakdown = buildCommercialBreakdown(results, options.pricingContext);
  const actions = breakdown.actions ?? [];
  const hasVerifiedPricing = !!options.pricingContext
    && Object.keys(options.pricingContext.itemsByReference).length > 0;

  if (actions.length > 0) {
    const lastY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 100;
    const startY = lastY + 15;

    doc.setFontSize(16);
    doc.text('2. Commercial Impact', margin, startY);
    if (!hasVerifiedPricing) {
      doc.setFontSize(9);
      doc.setTextColor(180, 83, 9);
      doc.text('Amounts pending: upload and verify project BQ and rate information before valuation.', margin, startY + 7);
      doc.setTextColor(0, 0, 0);
    }

    const topActions = [...actions]
      .sort((a, b) => Math.abs(b.amount ?? 0) - Math.abs(a.amount ?? 0))
      .slice(0, 20);

    autoTable(doc, {
      startY: startY + (hasVerifiedPricing ? 10 : 14),
      head: [['Action', 'Element', 'Qty', 'Unit', 'Rate (MYR)', 'Amount (MYR)']],
      body: topActions.map((a) => [
        a.action,
        a.component?.qsLabel ?? '',
        typeof a.quantity === 'number' ? a.quantity.toFixed(2) : '',
        a.unit ?? '',
        hasVerifiedPricing && typeof a.rate === 'number' ? a.rate.toFixed(2) : 'Pending verification',
        hasVerifiedPricing && typeof a.amount === 'number' ? a.amount.toLocaleString('en', { minimumFractionDigits: 2 }) : 'Pending verification',
      ]),
      theme: 'striped',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [59, 130, 246] },
      margin: { left: margin, right: margin },
    });
  }

  // ── Added Elements ──────────────────────────────────────────────────────────
  if (results.added.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.text('3. Added Elements (Additions)', margin, 25);

    autoTable(doc, {
      startY: 35,
      head: [['#', 'Type', 'QS Label', 'Section', 'Level']],
      body: results.added.slice(0, 50).map((c, i) => [
        String(i + 1),
        c.type ?? '',
        c.qsLabel ?? '',
        c.smm2SectionCode ?? '',
        c.levelName ?? '',
      ]),
      theme: 'striped',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [16, 185, 129] },
      margin: { left: margin, right: margin },
    });
  }

  // ── Deleted Elements ────────────────────────────────────────────────────────
  if (results.deleted.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.text('4. Deleted Elements (Omissions)', margin, 25);

    autoTable(doc, {
      startY: 35,
      head: [['#', 'Type', 'QS Label', 'Section', 'Level']],
      body: results.deleted.slice(0, 50).map((c, i) => [
        String(i + 1),
        c.type ?? '',
        c.qsLabel ?? '',
        c.smm2SectionCode ?? '',
        c.levelName ?? '',
      ]),
      theme: 'striped',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [239, 68, 68] },
      margin: { left: margin, right: margin },
    });
  }

  // ── Save ────────────────────────────────────────────────────────────────────
  const filename = `VO_Report_${(options.projectName ?? 'project').replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
