import { FINISH_TYPES, MEP_TYPES, OPENING_TYPES, ProjectQsOverrides, STRUCTURAL_TYPES, WALL_TYPES } from './qs-config';

export const PROJECT_QS_OVERRIDES: ProjectQsOverrides = {
  projectName: 'Default VO Project',
  currencySymbol: 'RM',
  sectionRules: [
    // Add project-first SMM2 mapping rules here when contract wording differs.
  ],
  materialRules: [
    // Add project-specific QS wording here.
  ],
  quantityNormalizationRules: [
    {
      id: 'section-f-concrete-net-volume',
      label: 'Section F Concrete Work - Net Volume rule',
      sectionCode: 'F',
      unit: 'm3',
      ifcTypes: STRUCTURAL_TYPES,
      strategies: ['concrete-net-volume', 'concrete-fallback-volume'],
    },
    {
      id: 'section-f-formwork-derived-area',
      label: 'Section F Formwork - Derived contact area rule',
      sectionCode: 'F',
      unit: 'm2',
      trigger: 'formwork-alert',
      ifcTypes: STRUCTURAL_TYPES,
      strategies: ['formwork-derived-area'],
    },
    {
      id: 'section-g-brickwork-net-area',
      label: 'Section G Brickwork - Net Area rule',
      sectionCode: 'G',
      unit: 'm2',
      ifcTypes: WALL_TYPES,
      strategies: ['brickwork-net-area', 'brickwork-volume-over-thickness'],
    },
    {
      id: 'section-m-finishes-net-area',
      label: 'Section M Finishes - Net Area rule',
      sectionCode: 'M',
      unit: 'm2',
      ifcTypes: FINISH_TYPES,
      strategies: ['finishes-net-area', 'finishes-volume-over-thickness'],
    },
    {
      id: 'section-q-item-count',
      label: 'Section Q Doors Windows - Item count rule',
      sectionCode: 'Q',
      unit: 'nr',
      ifcTypes: OPENING_TYPES,
      strategies: ['item-count'],
    },
    {
      id: 'section-u-item-count',
      label: 'Section U MEP - Item count rule',
      sectionCode: 'U',
      unit: 'nr',
      ifcTypes: MEP_TYPES,
      strategies: ['item-count'],
    },
  ],
  commercialRateRules: [
    {
      id: 'concrete-work-rate',
      label: 'Concrete work provisional rate',
      sectionCode: 'F',
      ifcTypes: STRUCTURAL_TYPES,
      quantityKeys: ['NetVolume', 'GrossVolume', 'Volume', 'BBoxVolumeEstimate'],
      unit: 'm3',
      rate: 420,
    },
    {
      id: 'formwork-rate',
      label: 'Formwork provisional rate',
      sectionCode: 'F',
      ifcTypes: STRUCTURAL_TYPES,
      unit: 'm2',
      rate: 185,
    },
    {
      id: 'brickwork-rate',
      label: 'Brickwork provisional rate',
      sectionCode: 'G',
      ifcTypes: ['IfcWall', 'IfcWallStandardCase'],
      quantityPatterns: [/area/i],
      unit: 'm2',
      rate: 95,
    },
    {
      id: 'finishes-rate',
      label: 'Finishes provisional rate',
      sectionCode: 'M',
      quantityPatterns: [/area/i, /surface/i],
      unit: 'm2',
      rate: 75,
    },
    {
      id: 'door-window-rate',
      label: 'Door and window provisional rate',
      sectionCode: 'Q',
      ifcTypes: ['IfcDoor', 'IfcWindow'],
      unit: 'nr',
      rate: 850,
    },
    {
      id: 'mep-item-rate',
      label: 'MEP installation provisional rate',
      sectionCode: 'U',
      ifcTypes: MEP_TYPES,
      unit: 'nr',
      rate: 650,
    },
  ],
  eotTriggerRules: [
    {
      id: 'imported-long-lead-change',
      title: 'Potential EOT Trigger: imported or long-lead specification changed',
      reason: 'Type / material / specification change suggests imported, bespoke, approval-heavy, or long-lead procurement risk.',
      recommendedAction: 'Review procurement lead time with Planner and consider EOT submission if the revised item affects approvals or delivery.',
      changedFields: ['typeSignature', 'materialSignature', 'predefinedType', 'description', 'attributes'],
      corpusPatterns: [/import/i, /imported/i, /italian/i, /german/i, /bespoke/i, /custom/i, /special.?order/i, /long.?lead/i, /lead.?time/i, /approval/i],
    },
    {
      id: 'mep-equipment-review',
      title: 'Potential EOT Trigger: MEP equipment or terminal specification changed',
      reason: 'MEP equipment / terminal reference changed and may require procurement, coordination, or authority re-submission.',
      recommendedAction: 'Review with Planner, M&E coordinator, and QS to determine whether EOT notice should accompany the VO claim.',
      ifcTypes: MEP_TYPES,
      changedFields: ['typeSignature', 'materialSignature', 'attributes'],
      corpusPatterns: [/pump/i, /fan/i, /ahu/i, /chiller/i, /terminal/i, /sanitary/i, /equipment/i, /valve/i, /switchboard/i, /manufacturer/i, /model/i],
    },
    {
      id: 'facade-door-window-review',
      title: 'Potential EOT Trigger: facade, door, or window system changed',
      reason: 'Opening / facade system change may affect fabrication drawings, approvals, and supplier lead time.',
      recommendedAction: 'Review shop-drawing, approval, and fabrication lead time impact with Planner before finalizing the VO.',
      ifcTypes: ['IfcDoor', 'IfcWindow', 'IfcCurtainWall', ...FINISH_TYPES],
      changedFields: ['typeSignature', 'materialSignature', 'attributes'],
      corpusPatterns: [/glazing/i, /facade/i, /curtain.?wall/i, /door/i, /window/i, /frame/i, /glass/i, /fire.?rating/i],
    },
  ],
  starRateBuildUpRules: [
    {
      id: 'brickwork-waterproof-star-rate',
      label: 'Brickwork star rate build-up - moisture resistant wall',
      sectionCode: 'G',
      ifcTypes: WALL_TYPES,
      corpusPatterns: [/waterproof/i, /moisture/i, /damp.?proof/i],
      materialLabel: 'Moisture-resistant brickwork material including waterproof additive',
      materialRate: 58,
      materialWastage: 0.05,
      materialNote: 'Seed market rate for waterproof brick and additive. Replace with supplier quotation before submission.',
      laborLabel: 'Bricklayer gang for moisture-resistant brickwork',
      laborOutputHoursPerUnit: 1.8,
      laborDayRate: 130,
      laborHoursPerDay: 8,
      laborNote: 'Seed output includes slower laying and joint control due to waterproofing requirement.',
      plantLabel: 'Access scaffold / lifting aids',
      plantRate: 0,
      plantNote: 'Leave blank unless scaffold revision, lifting plant, or special access is required.',
      overheadProfitPercent: 0.15,
    },
    {
      id: 'brickwork-standard-star-rate',
      label: 'Brickwork star rate build-up - standard walling',
      sectionCode: 'G',
      ifcTypes: WALL_TYPES,
      materialLabel: 'Common brickwork material in cement mortar (1:3)',
      materialRate: 42,
      materialWastage: 0.05,
      materialNote: 'Seed market rate for bricks, sand, cement, and mortar additives. Replace with project quotation.',
      laborLabel: 'Bricklayer gang output',
      laborOutputHoursPerUnit: 1.5,
      laborDayRate: 120,
      laborHoursPerDay: 8,
      laborNote: 'CTPO default output constant. Update with prevailing foreign labour daywork if required.',
      plantLabel: 'Scaffold / small plant allowance',
      plantRate: 0,
      plantNote: 'Leave blank unless special access, hoist, or temporary works are required.',
      overheadProfitPercent: 0.15,
    },
    {
      id: 'concrete-formwork-star-rate',
      label: 'Concrete / formwork star rate build-up',
      sectionCode: 'F',
      ifcTypes: STRUCTURAL_TYPES,
      materialLabel: 'Concrete / formwork material package',
      materialRate: 95,
      materialWastage: 0.03,
      materialNote: 'Use for abnormal geometry, special form-lining, release agents, and consumables. Adjust to supplier quotation.',
      laborLabel: 'Formwork carpenter gang output',
      laborOutputHoursPerUnit: 1.25,
      laborDayRate: 140,
      laborHoursPerDay: 8,
      laborNote: 'Seed output for abnormal geometry. Increase if access or repeatability is poor.',
      plantLabel: 'Formwork support / lifting plant',
      plantRate: 0,
      plantNote: 'Enter crane, tower crane, or special support plant if applicable.',
      overheadProfitPercent: 0.15,
    },
    {
      id: 'finishes-star-rate',
      label: 'Finishes star rate build-up',
      sectionCode: 'M',
      ifcTypes: FINISH_TYPES,
      materialLabel: 'Finish material package',
      materialRate: 55,
      materialWastage: 0.05,
      materialNote: 'Seed market rate for tiles, adhesive, grout, plaster, paint, or finish consumables. Update to supplier quotation.',
      laborLabel: 'Finishes gang output',
      laborOutputHoursPerUnit: 1.2,
      laborDayRate: 125,
      laborHoursPerDay: 8,
      laborNote: 'Use prevailing trade labour rate for tiler / plasterer / painter as required.',
      plantLabel: 'Small tools / access plant',
      plantRate: 0,
      plantNote: 'Leave blank unless special access or machinery is required.',
      overheadProfitPercent: 0.15,
    },
    {
      id: 'mep-star-rate',
      label: 'MEP star rate build-up',
      sectionCode: 'U',
      ifcTypes: MEP_TYPES,
      materialLabel: 'Equipment / terminal supply package',
      materialRate: 580,
      materialWastage: 0.02,
      materialNote: 'Seed market rate for supplied equipment or terminal including fittings. Replace with supplier quotation.',
      laborLabel: 'MEP installation labour',
      laborOutputHoursPerUnit: 0.75,
      laborDayRate: 145,
      laborHoursPerDay: 8,
      laborNote: 'Update with installation crew daywork for the actual trade.',
      plantLabel: 'Testing / access plant allowance',
      plantRate: 0,
      plantNote: 'Leave blank unless specialist lifting, testing, or access plant is needed.',
      overheadProfitPercent: 0.15,
    },
  ],
  shieldRateRules: [
    {
      id: 'brickwork-opening-shield',
      label: 'Brickwork non-deduction allowance',
      sectionCode: 'G',
      ruleIds: ['SMM2-G.3-OPENING-ND'],
      unit: 'm2',
      rate: 180,
    },
    {
      id: 'concrete-void-shield',
      label: 'Concrete non-deduction allowance',
      sectionCode: 'F',
      ruleIds: ['SMM2-F-VOID-ND'],
      unit: 'm3',
      rate: 650,
    },
  ],
  formworkTrigger: {
    enabled: true,
    applicableIfcTypes: STRUCTURAL_TYPES,
    maxVolumeDelta: 0.05,
    minSurfaceIncrease: 0.2,
    minSurfaceIncreaseRatio: 0.1,
    minPerimeterIncrease: 0.3,
    minMeshIncrease: 1,
  },
  voCoverSheet: {
    contractTitle: 'Proposed Works Contract',
    contractNumber: 'Contract Ref Pending',
    employer: 'Employer Name Pending',
    consultant: 'Superintending Officer / Consultant Pending',
    voReference: 'VO Ref Pending',
    revisionReference: 'Revision Ref Pending',
    preparedBy: 'QS Team',
    checkedBy: 'Commercial Manager',
  },
  typeFallbacks: {
    // Example:
    // IfcSanitaryTerminal: 'wash hand basin set',
  },
  nounOverrides: {
    // Exact `IfcType` or normalized object type keys are both supported.
  },
  locationAliases: {
    // Generic location aliases applied to all labels and paths.
    // Example:
    // 'Ground Floor': 'GF',
  },
  axisAliases: {
    // Example:
    // 'Grid A-1': 'A-1',
  },
  roomAliases: {
    // Example:
    // 'Male Toilet 01': 'MT-01',
  },
  zoneAliases: {
    // Example:
    // 'Wet Area Zone': 'Wet Area',
  },
  blockAliases: {
    // Example:
    // 'Tower A': 'Block A',
  },
  locationSelectors: {
    structural: 'axis',
    mep: 'room',
    opening: 'room',
    finish: 'room',
    default: 'level',
  },
};
